# Generated by Django 4.2.7 on 2023-11-27 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.TextField()),
                ("gdp", models.CharField(max_length=255)),
                ("kg_20", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_50", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_100", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_200", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_500", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("empresa", models.CharField(max_length=255)),
                ("pais", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("sector", models.CharField(max_length=255)),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=255)),
                ("producto", models.CharField(max_length=255)),
                ("ecologico", models.BooleanField(default=False)),
                ("certificaciones", models.TextField()),
                (
                    "pedido_minimo_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_500_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_1000_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ficha_tecnica",
                    models.FileField(
                        blank=True, null=True, upload_to="fichas_tecnicas/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("pais", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("eurohoja", models.BooleanField(default=False)),
                ("otras_certificaciones", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zona_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kg_50", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_100", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_200", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_300", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_400", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_500", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_1000", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_2000", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Zona_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kg_50", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_100", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_200", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_300", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_400", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_500", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_1000", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_2000", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Zona_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kg_50", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_100", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_200", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_300", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_400", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_500", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_1000", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_2000", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Zona_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kg_50", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_100", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_200", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_300", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_400", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_500", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_1000", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kg_2000", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("formato", models.CharField(max_length=10)),
                ("fecha_llegada_prevista", models.DateField()),
                ("fecha_llegada_final", models.DateField()),
                (
                    "precio_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.proveedor"
            ),
        ),
        migrations.CreateModel(
            name="PedidoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("formato", models.CharField(max_length=10)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pedido", models.DateField()),
                ("fecha_entrega_prevista", models.DateField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zona",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gasto_almacen", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gasto_distribucion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_final_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_final", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_total_iva",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_empresa",
                        to="website.cliente",
                    ),
                ),
                (
                    "precio_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.stock"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.proveedor",
                    ),
                ),
            ],
        ),
    ]
