# Generated by Django 4.2.7 on 2023-11-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.TextField()),
                ("gdp", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("pais", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("sector", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "costo_proveedor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_almacenamiento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("pais", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("eurohoja", models.BooleanField(default=False)),
                ("otras_certificaciones", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("precio_por_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costo_proveedor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_almacenamiento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("plazo_envio", models.CharField(max_length=10)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.almacen",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.cliente",
                    ),
                ),
                ("detalles_pedido", models.ManyToManyField(to="website.detallepedido")),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.proveedor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.producto"
            ),
        ),
        migrations.CreateModel(
            name="CosteEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso_hasta", models.IntegerField()),
                ("plazo_24h", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plazo_48_72h", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "costo_por_kilo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.zona"
                    ),
                ),
            ],
        ),
    ]
