# Generated by Django 4.2.7 on 2023-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
