# Generated by Django 4.2.7 on 2023-11-16 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="creado",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False
        ),
    ]
